<a href="https://colab.research.google.com/github/sushigva/Foundations-of-Data-Science-Repo/blob/Data-Science-Homework/homework/week-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 5

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

## 1. NumPy

You have three Python lists (below). Put them into a single NumPy `ndarray` as a 2-dimensional array (with 6 columns and 3 rows). Using the 6 columns in each list, add each column's values and print out the added values. Demonstrate everything required to code such an operation in the code block below.

```python
val1 = [12,14,16,18,20,22]
val2 = [5,10,15,20,25,30]
val3 = [5,7,9,11,13,15]
```

In [2]:
# Set up numpy and create an array from the 3 lists above. Don't just copy and
# paste the values into a new array by hand, use the three variables to create it.
import numpy as np

val1 = [12,14,16,18,20,22]
val2 = [5,10,15,20,25,30]
val3 = [5,7,9,11,13,15]

both_array = np.array([val1, val2, val3])

column_sums = np.sum(both_array, axis=0)

print("Column sums:")
print(column_sums)


Column sums:
[22 31 40 49 58 67]


In [9]:
# Now format a SINGLE command that displays the first and second lines of the ndarray you just made.
import numpy as np

val1 = [12, 14, 16, 18, 20, 22]
val2 = [5, 10, 15, 20, 25, 30]
val3 = [5, 7, 9, 11, 13, 15]

both_array = np.array([val1, val2, val3])

print("First and Second Lines:")
print(both_array[0:2, :])

First and Second Lines:
[[12 14 16 18 20 22]
 [ 5 10 15 20 25 30]]


In [3]:
# Format a command that slices the ndarray, giving only the first 3 columns of the first 2 rows.
# Display those values back in your code.
import numpy as np

val1 = [12, 14, 16, 18, 20, 22]
val2 = [5, 10, 15, 20, 25, 30]
val3 = [5, 7, 9, 11, 13, 15]

combined_array = np.array([val1, val2, val3])

combo = combined_array[:2, :3]

print("sliced (first 3 columns of the first 2 rows):")
print(combo)

sliced (first 3 columns of the first 2 rows):
[[12 14 16]
 [ 5 10 15]]


In [8]:
# Finally, using the ndarray object you created above, use the .T method with it.
# For example, if your ndarray was named "myarray" then issue this command:
#
#  myarray.T
#
# What does that command do to the ndarray? Write your answer in the text block below.

import numpy as np

val1 = [12, 14, 16, 18, 20, 22]
val2 = [5, 10, 15, 20, 25, 30]
val3 = [5, 7, 9, 11, 13, 15]

both_array = np.array([val1, val2, val3])

column_sums = np.sum(both_array, axis=0)

print("column sums:")
print(column_sums)

change_array = both_array.T

print("change array:")
print(change_array)



column sums:
[22 31 40 49 58 67]
change array:
[[12  5  5]
 [14 10  7]
 [16 15  9]
 [18 20 11]
 [20 25 13]
 [22 30 15]]


Answer here.

 The .T method reorganizes the array by changing the rows and columns like vice versa. It doesn't change the new array just makes a new one with the change one

# 2. Pandas

In class we created a DataFrame using the `read_csv` method. Another way to create a df is by hand, using Python lists. Below shows you how to do that, using a list of columns, a list of indexes, and a list of actual data for each record.

```python
df = pd.DataFrame(
    columns=['x','y','z'],
    index=['row1','row2','row3'],
    data=[[9,3,7],[1,2,4],[4,6,8]])
```

In [9]:
# Set up pandas and create the dataframe above. Then continue to work with the dataframe in the questions below.
import pandas as pd

df = pd.DataFrame(
    columns=['x', 'y', 'z'],
    index=['row1', 'row2', 'row3'],
    data=[[9, 3, 7], [1, 2, 4], [4, 6, 8]])

print(df)

      x  y  z
row1  9  3  7
row2  1  2  4
row3  4  6  8


In [10]:
# Format a command that displays the entire DataFrame.
print(df)

      x  y  z
row1  9  3  7
row2  1  2  4
row3  4  6  8


In [11]:
# Format a command that selects and returns only the SECOND row of data from the df.
second_row = df.loc['row2']
print(second_row)


x    1
y    2
z    4
Name: row2, dtype: int64


In [12]:
# Format a command that selects and returns only the `y` column of data from the df.
y_column = df['y']
print(y_column)

row1    3
row2    2
row3    6
Name: y, dtype: int64


In [13]:
# Format a command that displays the data types present in this DataFrame.
data_types = df.dtypes
print(data_types)

x    int64
y    int64
z    int64
dtype: object


In [22]:
# Finally, using the DataFrame object you created above, use the .T method with it.
# For example, if your df was named "mydf" then issue this command:
#
#  mydf.T
#
# What does that command do to the DataFrame? Write your answer in the text block below.

df = pd.DataFrame(
    columns=['x','y','z'],
    index=['row1','row2','row3'],
    data=[[9,3,7],[1,2,4],[4,6,8]])

df.T

row1  row2  row3
x     9     1     4
y     3     2     6
z     7     4     8

Answer here.

The DataFrame where the columns of df become rows, and the rows become columns.